const credits = [
  {
    "Engineering Mathematics-I": 4,
    "Engineering Physics": 4,
    "Human Values": 2,
    "Programming for Problem Solving": 2,
    "Basic Civil Engineering": 2,
    "Engineering Physics Lab": 1,
    "Human Values Activities": 1,
    "Computer Programming Lab": 1.5,
    "Basic Civil Engineering Lab": 1,
    "Computer Aided Engineering Graphics": 1.5,
    DECA: 0.5,
  },
  {
    "Engineering Mathematics-II": 4,
    "Engineering Chemistry": 4,
    "Communication Skills": 2,
    "Basic Mechanical Engineering": 2,
    "Basic Electrical Engineering": 2,
    "Engineering Chemistry Lab": 1,
    "Language Lab": 1,
    "Manufacturing Practices Workshop": 1.5,
    "Basic Electrical Engineering Lab": 1,
    "Computer Aided Machine Drawing": 1.5,
    DECA: 0.5,
  },
  {
    "Advanced Engineering Mathematics": 3,
    "Technical Communication": 2,
    "Engineering mechanics": 2,
    "Engineering thermodynamics": 3,
    "Material Science Engineering": 3,
    "Mechanics of solid": 4,
    "Machine Drawing lab": 1.5,
    "Material testing Lab": 1.5,
    "Basic Mechanical Engineering Lab": 1.5,
    "Programming through MATLab": 1.5,
    "Industrial Training": 1,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
  },
  {
    "Data Analytics": 2,
    "Managerial Economics Financial Accounting": 2,
    "Digital Electronics": 2,
    "Fluid Mechanics": 4,
    "Manufacturing process": 3,
    "Theory of Machine": 4,
    "Digital elctronics Lab ": 1.5,
    "Fluid Mechanics Lab": 1.5,
    "Production Practice Lab": 1.5,
    "Theory of Machine Lab": 1.5,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
  },
  {
    "Heat Transfer": 3,
    "Mechatronic System": 2,
    "MANUFACTURING TECHNOLOGY": 3,
    "DESIGN OF MACHINE ELEMENTS – I": 3,
    "PRINCIPLES OF MANAGEMENT": 2,
    "AUTOMOBILE ENGINEERING": 3,
    "MECHATRONICS LAB": 1,
    "HEAT TRANSFER LAB": 1,
    "PRODUCTION ENGINEERING LAB": 1,
    "MACHINE DESIGN PRACTICE - I": 1,
    "Industrial Training ": 2.5,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
  },
  {
    "Measurement & Metrology": 2,
    "CIMS": 3,
    "Mechanical Vibration": 2,
    "DESIGN OF MACHINE ELEMENTS – II": 3,
    "Quality Management": 2,
    "CIMS Lab": 3,
    "Vibration Lab": 2,
    "Machine Design Practice-II": 1.5,
    "Thermal Engineering Lab-I": 1.5,
    "NCMM": 1.5,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
  },
  {
    "Environmental Engineering & Disaster Management": 3,
    "Internet Of Things": 3,
    "Internet Of Things Lab": 2,
    "Cyber Security Lab": 2,
    "Industrial Training": 2.5,
    Seminar: 2,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
  },
  {
    "Big Data Analytics": 3,
    "Big Data Analytics Lab": 2,
    "Software Testing & Validation Lab": 1,
    Project: 7,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
    "Disaster Management": 3,
  },
];

export default credits;
