const credits = [
  {
    "Engineering Mathematics-I": 4,
    "Engineering Physics": 4,
    "Human Values": 2,
    "Programming for Problem Solving": 2,
    "Basic Civil Engineering": 2,
    "Engineering Physics Lab": 1,
    "Human Values Activities": 1,
    "Computer Programming Lab": 1.5,
    "Basic Civil Engineering Lab": 1,
    "Computer Aided Engineering Graphics": 1.5,
    DECA: 0.5,
  },
  {
    "Engineering Mathematics-II": 4,
    "Engineering Chemistry": 4,
    "Communication Skills": 2,
    "Basic Mechanical Engineering": 2,
    "Basic Electrical Engineering": 2,
    "Engineering Chemistry Lab": 1,
    "Language Lab": 1,
    "Manufacturing Practices Workshop": 1.5,
    "Basic Electrical Engineering Lab": 1,
    "Computer Aided Machine Drawing": 1.5,
    DECA: 0.5,
  },
  {
    "Advanced Engineering Mathematics": 3,
    "Technical Communication": 2,
    "Engineering mechanics": 2,
    "Engineering thermodynamics": 3,
    "Material Science Engineering": 3,
    "Mechanics of solid": 4,
    "Machine Drawing lab": 1.5,
    "Material testing Lab": 1.5,
    "Basic Mechanical Engineering Lab": 1.5,
    "Programming through MATLab": 1.5,
    "Industrial Training": 1,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
  },
  {
    "Data Analytics": 2,
    "Managerial Economics Financial Accounting": 2,
    "Digital Electronics": 2,
    "Fluid Mechanics": 4,
    "Manufacturing process": 3,
    "Theory of Machine": 4,
    "Digital elctronics Lab ": 1.5,
    "Fluid Mechanics Lab": 1.5,
    "Production Practice Lab": 1.5,
    "Theory of Machine Lab": 1.5,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
  },
  {
    "Information Theory & Coding": 2,
    "Compiler Design": 3,
    "Operating System": 3,
    "Computer Graphics & Multimedia": 3,
    "Analysis of Algorithms": 3,
    "Human-Computer Interaction": 2,
    "Computer Graphics & Multimedia Lab": 1,
    "Compiler Design Lab": 1,
    "Analysis of Algorithms Lab": 1,
    "Advance Java Lab": 1,
    "Industrial Training ": 2.5,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
  },
  {
    "Digital Image Processing": 2,
    "Machine Learning": 3,
    "Information Security Systems": 2,
    "Computer Architecture and Organization": 3,
    "Artificial Intelligence": 2,
    "Cloud Computing": 3,
    "Distributed Systems": 2,
    "Digital Image Processing Lab": 1.5,
    "Machine Learning Lab": 1.5,
    "Python Lab": 1.5,
    "Mobile App Development Lab": 1.5,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
  },
  {
    "Environmental Engineering & Disaster Management": 3,
    "Internet Of Things": 3,
    "Internet Of Things Lab": 2,
    "Cyber Security Lab": 2,
    "Industrial Training": 2.5,
    Seminar: 2,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
  },
  {
    "Big Data Analytics": 3,
    "Big Data Analytics Lab": 2,
    "Software Testing & Validation Lab": 1,
    Project: 7,
    "Social Outreach, Discipline & Extracurricular Activities": 0.5,
    "Disaster Management": 3,
  },
];

export default credits;
